### ISSUE TITLE
income basis calculation

### ISSUE THREAD

**Issue by apeironn8** [alexpung/taxCalculator#2]
Hi 
this is great, I'm looking for a solution to calculate tax on a income basis rather than capital gains, 

would be great to have an option for that!

thanks

**Comment by alexpung** [comment]
The project does not calculate the tax owed. It just use the trade matching rules to calculate taxable income/loss.
In case of dividends it simply tally up the dividends by the company country.

Income basis not sure if it is the same matching rules. Please check the tax law.
